project:
  type: website
  output-dir: _site
  resources:
    - cv.pdf

website:
  title: "Yanwan Zhu"
  site-url: "https://yanwanz.github.io"
  image: profile.jpg
  open-graph: true
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: about
      - href: research.qmd
        text: research
      - href: teaching.qmd
        text: teaching

format:
  html:
    theme:
      light: [cosmo, custom.scss, light.scss]
      dark: [cosmo, custom.scss, dark.scss]
    toc: false