project:
  type: website
  output-dir: _site
  resources:
    - cv.pdf

website:
  title: "Yanwan Zhu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false