project:
  type: website
  output-dir: _site
  resources:
    - cv.pdf

website:
  title: "Yanwan Zhu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme:
      light: [cosmo, custom.scss, light.scss]
      dark: [cosmo, custom.scss, dark.scss]
    toc: false